# The following can be used to restrict the colour palettes of the elemental
# if not set, users will be able to select all hex colours available
# MySiteDigital\Elements\ElementQuoteBanner:
#   bg_colour_pallette:
#     - '#333444'
#     - '#e3e4e5'
#     - '#abcabc'
#   text_colour_pallette:
#     - '#fefefe'
#     - '#defa57'
